spring:
  config:
    import: "optional:file:/app/config/app.env.properties"
  application:
    name: bmtool1

server:
  port: ${BACKEND_PORT}
  error:
    include-message: always
    include-binding-errors: always


bmtool1:
  weaviate:
    url: http://weaviate:${WEAVIATE_PORT}
    className: ${WEAVIATE_CLASS_NAME:PairChunk}
  ollama:
    url: http://ollama:${OLLAMA_PORT}
    embeddingModel: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text} #default model #todo: delete this
  openrouter:
    apiKey: ${OPENROUTER_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.learningjava.bmtool1: ${APP_LOG_LEVEL:DEBUG}

#todo
ingest:
  on-replace: ${INGEST_ON_REPLACE:true}
  rootDir: ${INGEST_ROOT_DIR:/app/data/pairs}


#todo automatic restart not working

