spring:
  config:
    import:
      - optional:file:/app/config/app.env.properties
      - optional:configtree:../secrets/
  application:
    name: bmtool1
  datasource:
    url: jdbc:postgresql://db:${POSTGRES_PORT:5432}/bmtool
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1

server:
  port: ${BACKEND_PORT:1000}
  error:
    include-message: always
    include-binding-errors: always

bmtool1:
  weaviate:
    url: http://weaviate:${WEAVIATE_PORT:8080}
    className: ${WEAVIATE_CLASS_NAME:PairChunk}
  ollama:
    url: http://ollama:${OLLAMA_PORT:11434}
    embeddingModel: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
  openrouter:
    apiKey: ${openrouter_api_key:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.learningjava.bmtool1: ${APP_LOG_LEVEL:DEBUG}

ingest:
  on-replace: ${INGEST_ON_REPLACE:true}
  rootDir: ${INGEST_ROOT_DIR:/app/data/pairs}
